package com.iwrite.audit.entity;

public enum AuditAction {
    BOOK_CREATED,
    BOOK_UPDATED,
    BOOK_DELETED,
    SCENE_CREATED,
    SCENE_UPDATED,
    SCENE_CONTENT_UPDATED,
    SCENE_PLANNING_UPDATED,
    SCENE_DELETED,
    COLLABORATOR_ADDED,
    COLLABORATOR_REMOVED,
    SCENE_VERSION_RESTORED,
    OPENAI_SCENE_ANALYSIS
}
